# Generated by Django 3.2.4 on 2021-08-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galary',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
