# Generated by Django 3.2.4 on 2021-08-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galary', '0002_alter_galary_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galary',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
    ]
