# Generated by Django 3.2.4 on 2021-08-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galary', '0003_alter_galary_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galary_fasttest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('a', 'Куплю'), ('c', 'продам'), ('b', 'обменяю')], default='s', max_length=1)),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
    ]
