# Generated by Django 3.2.4 on 2021-08-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galary', '0004_galary_fasttest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galary_fasttest',
            options={'verbose_name': 'Галерея_test', 'verbose_name_plural': 'Галерея_test'},
        ),
        migrations.AddField(
            model_name='galary_fasttest',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
