# Generated by Django 3.2.4 on 2021-08-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galary', '0006_alter_galary_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galary',
            name='photo_url',
            field=models.TextField(verbose_name='Ссылка на фотографию'),
        ),
    ]
