# Generated by Django 3.2.4 on 2021-08-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название детали')),
                ('coast', models.FloatField(verbose_name='Цена детали')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет детали')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
            },
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Номер карты', 'verbose_name_plural': 'Номера карты'},
        ),
        migrations.AlterField(
            model_name='user',
            name='cards_number',
            field=models.ManyToManyField(to='Bank.Card', verbose_name='Номера карт'),
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название машины')),
                ('color', models.CharField(max_length=80, verbose_name='Цвет машины')),
                ('coast', models.FloatField(verbose_name='Цена Машины')),
                ('details', models.ManyToManyField(to='Bank.Details')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
