# Generated by Django 3.2.4 on 2021-08-11 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_articles_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_articles',
            name='comments',
        ),
        migrations.AddField(
            model_name='blog_comments',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog_articles', verbose_name='Статья'),
        ),
    ]
