# Generated by Django 3.2.4 on 2021-09-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_articles_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles_autor',
            options={'ordering': ['-autor']},
        ),
    ]
